version: '3.4'

networks:
  hypothyrobot-dev:
    driver: bridge 

services:
  hypothyrobot:
    image: eternalspring/hypothyrobot:latest
    depends_on:
      - "host.docker.internal"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"   
    environment:
      DB_CONNECTION_STRING: "host=host.docker.internal;port=5432;database=usersdb;username=postgres;password=elpsycongroo"
    networks:
      - hypothyrobot-dev  
    extra_hosts:
      - "host.docker.internal:host-gateway"

  host.docker.internal:
    image: postgres:latest
    ports:
      - "5432"
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "elpsycongroo"
      POSTGRES_DB: "usersdb"
    networks:
      - hypothyrobot-dev
volumes:
  db_volume:
         
    